# Generated by jPipe
# Source : final.jd
# Date   : 2026-04-25T23:31:18.262065Z

from typing import Any, Callable
from jpipe_runner.framework.decorators.jpipe_decorator import jpipe
from jpipe_runner.framework.decorators.link_decorator import jpipe_link

JpipeProduce = Callable[[str, Any], None]

# jpipe-runner --library steps/final.py --diagram final --format svg final.json

mock = {
    'model_file':   'https://huggingface.co/boltuix/bert-emotion',
    'test_dataset': 'tests.csv',
    'accuracy':     0.82,
    'counterfacts': 'counterfacts.csv',
    'flip_rate':    0.08
}

#################
#### Shared #####
#################

@jpipe_link("final:deployable:assembleStrategy")
@jpipe(produce=[], consume=["performant", "fair"])
def all_conditions_are_met(performant: bool, fair: bool, 
                           produce: JpipeProduce) -> bool:
    """[strategy] All conditions are met"""
    return performant and fair


######################
#### Performance #####
######################

@jpipe_link("final:deployable:performant:c")
@jpipe(produce=["performant"], consume=[])
def my_model_is_performant(produce: JpipeProduce) -> bool:
    """[sub-conclusion] My model is performant"""
    produce('performant', True)
    return True


@jpipe_link("final:deployable:performant:s")
@jpipe(consume=["model", "tests", "converged"], produce=[])
def accuracy_is_greater_than_80(model: str, tests: str,
                                converged: bool,
                                produce: JpipeProduce) -> bool:
    """[strategy] Accuracy is greater than 80"""
    # We're pretending loading the model
    model_ok = converged and model.startswith('https')
    # We're pretending loading the dataset
    dataset_ok = tests.endswith('.csv')
    # We're pretending evaluating the model using the dataset
    accuracy_ok = ('accuracy' in mock) and mock['accuracy'] > 0.80
    return model_ok and dataset_ok and accuracy_ok


@jpipe_link("final:deployable:performant:e2")
@jpipe(produce=["tests"])
def test_dataset_is_available(produce: JpipeProduce) -> bool:
    """[evidence] Test dataset is available"""
    if (found := 'test_dataset' in mock):
        produce('tests', mock['test_dataset'])
    return found 


###################
#### Fairness #####
###################

@jpipe_link("final:deployable:fair:c")
@jpipe(produce=["fair"], consume=[])
def my_model_is_fair(produce: JpipeProduce) -> bool:
    """[sub-conclusion] My model is fair"""
    produce('fair', True)
    return True

@jpipe_link("final:deployable:fair:s")
@jpipe(consume=["counterfactual", "model", "converged"], produce=[])
def assess_counterfactual_fairness(counterfactual: str, model: str,
                                   converged: bool, 
                                   produce: JpipeProduce) -> bool:
    """[strategy] Assess counterfactual fairness"""
    # We're pretending loading the model
    model_ok = converged and model.startswith('https')
    # We're pretending loading the dataset
    counterfactual_ok = counterfactual.endswith('.csv')
    # We're pretending evaluating the model using the dataset
    flip_rate_ok = ('flip_rate' in mock) and mock['flip_rate'] < 0.2
    return model_ok and counterfactual_ok and flip_rate_ok

@jpipe_link("final:deployable:fair:e2")
@jpipe(produce=["counterfactual"])
def counterfactual_dataset_is_available(produce: JpipeProduce) -> bool:
    """[evidence] Counterfactual dataset is available"""
    if (found := 'counterfacts' in mock):
        produce('counterfactual', mock['counterfacts'])
    return found  


#####################
#### Convergence ####
#####################

@jpipe_link("final:hook")
@jpipe(produce=["converged"], consume=[])
def the_trained_model_converges(produce: JpipeProduce) -> bool:
    """[sub-conclusion] The trained model converges"""
    produce('converged', True)
    return True


@jpipe_link("final:convergence:check_convergence")
@jpipe(produce=[], consume=["logs", "model"])
def assessing_logs_to_measure_convergence(logs: bool, model: bool, 
                                          produce: JpipeProduce) -> bool:
    """[strategy] Assessing logs to measure convergence"""
    return model and logs

@jpipe_link("final:convergence:e2")
@jpipe(produce=["logs"])
def intermediate_logs_are_available(produce: JpipeProduce) -> bool:
    """[evidence] Intermediate logs are available"""
    produce('logs', True)
    return True

@jpipe_link("final:convergence:e1")
@jpipe(produce=["model"])
def trained_model_is_available(produce: JpipeProduce) -> bool:
    """[evidence] Trained model is available"""
    if (found := 'model_file' in mock):
        produce('model', mock['model_file'])
    return found  
