# Generated by jPipe
# Source : deployable.jd
# Date   : 2026-04-25T22:45:40.566345Z

from typing import Any, Callable
from jpipe_runner.framework.decorators.jpipe_decorator import jpipe
from jpipe_runner.framework.decorators.link_decorator import jpipe_link

JpipeProduce = Callable[[str, Any], None]

# jpipe-runner --library steps/deployable.py --model deployable --format svg deployable.json

mock = {
    'accuracy':     0.82,
    'model_file':   'https://huggingface.co/boltuix/bert-emotion',
    'test_dataset': 'tests.csv',
    'counterfacts': 'counterfacts.csv'
}

#################
#### Shared #####
#################

@jpipe_link("deployable:assembleConclusion")
@jpipe(consume=[])
def model_is_deployable() -> bool:
    """[conclusion] Model is deployable"""
    return True

@jpipe_link("deployable:assembleStrategy")
@jpipe(produce=[], consume=[])
def all_conditions_are_met(produce: JpipeProduce) -> bool:
    """[strategy] All conditions are met"""
    return True

@jpipe_link("deployable:unified_0")
@jpipe(produce=["model"])
def model_is_available(produce: JpipeProduce) -> bool:
    """[evidence] Model is available"""
    if (found := 'model_file' in mock):
        produce('model', True)
    return found  

######################
#### Performance #####
######################

@jpipe_link("deployable:performant:c")
@jpipe(produce=[], consume=["accuracy"])
def my_model_is_performant(produce: JpipeProduce) -> bool:
    """[sub-conclusion] My model is performant"""
    return True


@jpipe_link("deployable:performant:s")
@jpipe(consume=["model", "tests"], produce=["accuracy"])
def accuracy_is_greater_than_85(model: bool, tests: bool,
                                produce: JpipeProduce) -> bool:
    """[strategy] Accuracy is greater than 85"""
    if (ok := model and tests and mock['accuracy'] > 0.85):
        produce("accuracy", mock['accuracy'])
    return ok

@jpipe_link("deployable:performant:e2")
@jpipe(produce=["tests"])
def test_dataset_is_available(produce: JpipeProduce) -> bool:
    """[evidence] Test dataset is available"""
    if (found := 'test_dataset' in mock):
        produce('tests', True)
    return found  

###################
#### Fairness #####
###################

@jpipe_link("deployable:fair:c")
@jpipe(produce=[], consume=["fair"])
def my_model_is_fair(fair: bool, produce: JpipeProduce) -> bool:
    """[sub-conclusion] My model is fair"""
    return True


@jpipe_link("deployable:fair:s")
@jpipe(consume=["counterfactual", "model"], produce=["fair"])
def assess_counterfactual_fairness(counterfactual: str, model: str,
                                   produce: JpipeProduce) -> bool:
    """[strategy] Assess counterfactual fairness"""
    produce('fair', True)
    return counterfactual and model

@jpipe_link("deployable:fair:e2")
@jpipe(produce=["counterfactual"])
def counterfactual_dataset_is_available(produce: JpipeProduce) -> bool:
    """[evidence] Counterfactual dataset is available"""
    if (found := 'counterfacts' in mock):
        produce('counterfactual', True)
    return found  
