# Generated by jPipe
# Source : performant.jd
# Date   : 2026-04-16T15:14:16.041469Z

from typing import Any, Callable
from jpipe_runner.framework.decorators.jpipe_decorator import jpipe
from jpipe_runner.framework.decorators.link_decorator import jpipe_link

JpipeProduce = Callable[[str, Any], None]


# jpipe-runner --library steps/performant.py --diagram performant --format svg performant.json

mock = {
    'model_file':   'https://huggingface.co/boltuix/bert-emotion',
    'test_dataset': 'tests.csv',
    'accuracy':     0.92
}

@jpipe_link("performant:s")
@jpipe(consume=["model", "tests"], produce=[])
def accuracy_is_greater_than_85(model: str, tests: str,
                                produce: JpipeProduce) -> bool:
    """[strategy] Accuracy is greater than 85"""
    # We're pretending loading the model
    model_ok = model.startswith('https')
    # We're pretending loading the dataset
    dataset_ok = tests.endswith('.csv')
    # We're pretending evaluating the model using the dataset
    accuracy_ok = ('accuracy' in mock) and mock['accuracy'] > 0.85
    return model_ok and dataset_ok and accuracy_ok


@jpipe_link("performant:e1")
@jpipe(produce=["model"])
def model_is_available(produce: JpipeProduce) -> bool:
    """[evidence] Model is available"""
    if (found := 'model_file' in mock):
        produce('model', mock['model_file'])
    return found  


@jpipe_link("performant:e2")
@jpipe(produce=["tests"])
def test_dataset_is_available(produce: JpipeProduce) -> bool:
    """[evidence] Test dataset is available"""
    if (found := 'test_dataset' in mock):
        produce('tests', mock['test_dataset'])
    return found 


