# Generated by jPipe
# Source : performant.jd
# Date   : 2026-04-16T15:14:16.041469Z

from typing import Any, Callable
from jpipe_runner.framework.decorators.jpipe_decorator import jpipe
# from jpipe_runner.framework.decorators.jpipe_decorator import jpipe_link

JpipeProduce = Callable[[str, Any], None]


# jpipe-runner --library steps/performant.py --diagram performant --format svg performant.json

mock = {
    'accuracy':     0.92,
    'model_file':   'https://huggingface.co/boltuix/bert-emotion',
    'test_dataset': 'tests.csv'
}


# @jpipe_link("performant:c")
@jpipe(consume=["accuracy"])
def my_model_is_performant() -> bool:
    """[conclusion] My model is performant"""
    return True


# @jpipe_link("performant:s")
@jpipe(consume=["model", "tests"], produce=["accuracy"])
def accuracy_is_greater_than_85(model: bool, tests: bool,
                                produce: JpipeProduce) -> bool:
    """[strategy] Accuracy is greater than 85"""
    if (ok := model and tests and mock['accuracy'] > 0.85):
        produce("accuracy", mock['accuracy'])
    return ok


# @jpipe_link("performant:e1")
@jpipe(produce=["model"])
def model_is_available(produce: JpipeProduce) -> bool:
    """[evidence] Model is available"""
    if (found := 'model_file' in mock):
        produce('model', True)
    return found  


# @jpipe_link("performant:e2")
@jpipe(produce=["tests"])
def test_dataset_is_available(produce: JpipeProduce) -> bool:
    """[evidence] Test dataset is available"""
    if (found := 'test_dataset' in mock):
        produce('tests', True)
    return found 


