name: jPipe Runner Workflow -- Step 05

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  jpipe-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Run jPipe Runner
        uses: jpipe-mcscert/jpipe-runner@v3.4.1
        with:
          version: v3.4.1
          embed_image: "true"
          image_branch: "diagram-images"
          jd_file: step_05/final.json
          library: step_05/steps/final.py
          github-token: ${{ secrets.GITHUB_TOKEN }}